inherit_from:
- .rubocop_airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数の上限を８０文字から変更
Layout/LineLength:
  Max: 130

#rubocopで最新のルールを適用する&検証したくないフォルダを指定
AllCops:
  NewCops: enable
  Exclude:
    - 'app/channels/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
